### ISSUE TITLE
dsdlc: C++ headers generated for union type definitions should be C++ unions themselves, not structs

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunavut#105]
Currently, the DSDL compiler turns DSDL union definitions into C++ structs, which causes the memory footprint to be a sum of that of the contained fields. This is really inefficient.

The DSDL compiler should use an aliased memory storage in order to reduce the size of the resulting type.

**Comment by thirtytwobits** [comment]
Will close this shortly as I merge in updated C++ POD generation. I'll open a separate ticket to consider variants.
