### ISSUE TITLE
Option to allow allow_unregulated_fixed_port_id (0.3.4)

### ISSUE THREAD

**Issue by nacansino** [UAVCAN/nunavut#126]
**Nunavut Version**
0.3.4

**Details:**
As the title says. 

I encountered the error `raise UnregulatedFixedPortIDError` when generating C-headers against a DSDL namespace root:
\root
|---100.PointXY.1.0.uavcan
|---MyService.1.0.uavcan

100 should be counted as unregulated identifiers as per Table 5.1 in the UAVCAN specification.

I don't know if this was intended or not, but it seems that Nunavut is calling `pydsdl` with the default argument `allow_unregulated_fixed_port_id: bool=False`

inside cli.py:
```python
...
    #
    # nunavut : parse
    #
    type_map = pydsdl.read_namespace(args.root_namespace, extra_includes)
...
```

**Possible solution:**
Expose the allow_unregulated_fixed_port_id argument on nnvg?

**Comment by thirtytwobits** [comment]
Oh weird. I thought I did that already. This is an easy thing to add.

**Comment by thirtytwobits** [comment]
released
