### ISSUE TITLE
Generated path on #include uses backslashes when generated on Windows

### ISSUE THREAD

**Issue by nacansino** [UAVCAN/nunavut#129]
**Nunavut Version:**
0.3.4

**Description of the problem**
As the title says.
I generated C headers on a Windows machine. All was well except today when I moved into my workstation that uses Linux and pulled the headers from an online repo where the build failed miserably due to unresolved include paths.

**Proposed Solution:**
I suggest we use forward slashes in our #include paths regardless of the host generator.

**Comment by thirtytwobits** [comment]
Looks like we're not using pathlib somewhere in the code. Should be easy to find this.
