### ISSUE TITLE
Generation of C regulated data types results in infinite recursion.

### ISSUE THREAD

**Issue by davidlenfesty** [UAVCAN/nunavut#130]
I'm going to try and come up with a fix for this, but for reference:

When attempting to generate the regulated data types (`public_regulated_data_types/regulated`), we run into infinite recursion.

This occurs in the current master as well as in PR #115.

The stack trace points to infinite recursion of the `init_field` macro in `lang/c/templates/_init_macros.j2`. (https://pastebin.com/wk9rjCNv), with a few print statements it fails on `regulated.zubax.sensor.bms.BatteryPackParams`, within the `data_type_init()` function. Notably the call to `init_field` is recursive, and dependant on a foreach on a data type.

```
static inline void regulated_zubax_sensor_bms_BatteryPackParams_0_1_init(regulated_zubax_sensor_bms_BatteryPackParams_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_si_unit_mass_Scalar_1_0_init(&(out_instance->mass));
        uavcan_si_unit_electric_charge_Scalar_1_0_init(&(out_instance->design_capacity));
        uavcan_si_unit_electric_current_Scalar_1_0_init(&(out_instance->design_load_current));
[EOF]
```

I've seen it mentioned twice, [in PR #115](https://github.com/UAVCAN/nunavut/pull/115#issuecomment-678115391), and [on the forum](https://forum.uavcan.org/t/generating-c-headers-of-regulated-dsdl/920).

**Comment by thirtytwobits** [comment]
We need to add a unit tests that reproduces this issue to verify that the fix works and to catch and future regressions.

**Comment by thirtytwobits** [comment]
It's interesting that I'm not seeing a recursion problem in my tests. I see incorrect code generated (i.e. syntax error) but the code is generated.
