### ISSUE TITLE
support headers cause problems with build scripts

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunavut#134]
when using multiple roots (i.e. uavcan and something else) each invocation of nnvg will provide the same serialization.h (for c) output. When using modern build systems like Make or CMake this will tend to cause duplicate targets to be created which is bad.

We could provide a flag to suppress support header generation but still generate serialization code for the types. This is an easy fix but it doesn't ensure that the two invocations of nnvg would have resulted in the exact same serialization header generated. To help with this would could add a mode that **only** generated the serialization header. This allows build script authors to setup dependencies from multiple header generation targets that depend on the serialization target header. Personally I'd just always elect the core type rule to generate this header but that might not be a fully generalized solution.

**Comment by pavel-kirienko** [comment]
Can we make Nunavut check if the destination directory already contains `nunavut.h` and rewrite it only if the new file would be different? In this case, no extra options would need to be added to the user interface, as I see it.

**Comment by thirtytwobits** [comment]
I think this is an easy fix. Make only whines about this but ninja users will be blocked by it.

**Comment by thirtytwobits** [comment]
We need to fix this. It could block some users right out of the gate.

**Comment by pavel-kirienko** [comment]
@thirtytwobits Do you think it's doable by Dec 23rd?

**Comment by thirtytwobits** [comment]
Yes

**Comment by thirtytwobits** [comment]
Got a working prototype. The only way to do this is the correct way; I'm adding an argument `--generate-support` with the following options:

```
    as-needed (default) - generate support code if serialization is enabled.
    always - always generate support code.
    never - never generate support code.
    only - only generate support code.
```

build scripts can then create dependencies like:

```
`nnvg --generate-support=only --list-outputs` : `nnvg --generate-support=only --list-inputs` ;

`nnvg --generate-support=never -e .h path/to/types --list-outputs` : `nnvg --generate-support=never -e .h path/to/types --list-inputs` `nnvg --generate-support=only --list-outputs` ;

```

which is psedo-makefile syntax for "serialization.h is build from serialization.j2 and each of my generated headers is built from  the dsdl files and the nunvut c templates which all depend on serialization.h". Build scripts can have a single rule to generate everything in one go or can split generation up into per-root-namespace rules that depend on a stand-along support code generation rule.

Still TODO:

1. testing
2. For c, generate macros in serialization.h that declare the language options used to generate it.
3. Using (2), create asserts in all generated code – when including serialization.h – that prevents compiling against a serialization.h generated with incompatible language options.
