### ISSUE TITLE
Who (if anyone) is responsible for zero-clearing voidx DSDL fields when doing C serialisation

### ISSUE THREAD

**Issue by aentinger** [UAVCAN/nunavut#139]
I'd like to file a bug report/question concerning PR #115 / 52751e3034fd96793dd78a51c75de65c5fbad4fb. (I'm not sure whether it's a real bug or me not fully understanding something).

The issue I have observed is the following: When using `uavcan_node_ExecuteCommand_1_0_Response_serialize` as generated by `nnvg` and `https://github.com/UAVCAN/public_regulated_data_types` via `nnvg --outdir include --templates c_jinja --pp-trim-trailing-whitespace -e .h uavcan`

the function only set's the first 8 bits and leaves the remaining 6 bytes of `out_buffer` as it was before `out_buffer` was passed to the function. This has the curious side effect that the values in `out_buffer[0-6]` are whatever is left in the memory region where `out_buffer` lives - **and not 0 as one might expect**.

```C
static inline int32_t uavcan_node_ExecuteCommand_1_0_Response_serialize(const uavcan_node_ExecuteCommand_1_0_Response* in_instance, uint32_t offset, uint8_t* const out_buffer)
{

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }

    // Begin Structure: saturated uint8
    nunavutSetUxx(out_buffer, offset, in_instance->status, 8);
    offset += 8;
    // End Structure: saturated uint8
    // Begin Structure: void48
    offset += 48;
    // End Structure: void48

    return offset;
}
```

So the question is: Is the caller responsible for zero-clearing that buffer or will the function be augmented to zero-clear such `voidx` statements as found e.g. in the DSDL for `ExecuteCommand_1_0_Response`?

**Comment by pavel-kirienko** [comment]
The output of the serialization function should be invariant to the original state of the buffer. I imagine it's one of the things that are not yet finished in that PR. A stop-gap solution could be to `memset()` but ultimately it's up to David & Scott.

**Comment by aentinger** [comment]
My quick-fix is to [zero-clear](https://github.com/107-systems/107-Arduino-UAVCAN/commit/83d592aa948afda555b022e0369bb2a17d1a1ac8) the payload buffer within the caller code. I'll probably leave it 
 that way regardless of the final outcome of #115 as it's a very cheap safe-guard.

**Comment by thirtytwobits** [comment]
based on the specification, section 3.4.1:

> Void-typed field attributes are set to zero when an object is serialized and ignored when it is deserialized. Void types can be used to reserve space in data type definitions for possible use in later versions of the data type.

so the issue is we need to zero void in the serialize method. For deserialization (for C, as C++ deserialization is not yet implemented) the initializers generated for each type zero these fields but the deserialization method does not call these initializers. Doing so would force a certain amount of overhead on the caller whereas the current method provides more flexability. So, for example, you can do this:

```
uavcan_si_unit_velocity_Vector3_1_0 foo;

uavcan_si_unit_velocity_Vector3_1_0_init(&foo);
if (uavcan_si_unit_velocity_Vector3_1_0_deserialize(&foo, 0, buffer, buffer_length_bytes))
{
    ...
}
```

------

if Pavel had let me use my fluent initializers you would have been able to do this:
```
uavcan_si_unit_velocity_Vector3_1_0 foo;

if (uavcan_si_unit_velocity_Vector3_1_0_deserialize(uavcan_si_unit_velocity_Vector3_1_0_init(&foo),
                                                    0,
                                                    buffer,
                                                    buffer_length_bytes))
{
    ...
}
```

but I'm not bitter or anything :)

**Comment by pavel-kirienko** [comment]
> if Pavel had let me use my fluent initializers you would have been able to do this

C is the wrong language to write nice things in

**Comment by aentinger** [comment]
I'm glad to hear that per **section 3.4.1** void type fields should be set to zero since that's also what `pyuavcan` does when I use it to generate CAN frames for feeding my unit tests. I'm closing this issue since it should be handled as per #115 / b6711302ea8e99abdf0aee71dd15f53f1739fd54 .
