### ISSUE TITLE
using -e instead of --target-language does not generate the float serialization

### ISSUE THREAD

**Issue by nacansino** [UAVCAN/nunavut#142]
Hi guys,

I found an inconsistency (?) when invoking `nnvg` using the `-e OUTPUT_EXTENSION` instead of the `--target-language`.
In the former, the language options target_endianness, `omit_float_serialization_support`, and `enable_serialization_asserts` parsed (or defaulted) by `argparse`  are not assigned to the language context.
Looking at the source `cli.py`, it seems that the program checks if `target-language` is set before it assigns the appropriate language options to language_context.

```python
if args.target_language is not None:
        language_options = dict()
        if args.target_endianness is not None:
            language_options['target_endianness'] = args.target_endianness
        language_options['omit_float_serialization_support'] = False
        language_options['enable_serialization_asserts'] = args.enable_serialization_asserts

language_context = nunavut.lang.LanguageContext(
        args.target_language,
        args.output_extension,
        args.namespace_output_stem,
        omit_serialization_support_for_target=args.omit_serialization_support,
        language_options=language_options)
```

As a result, the source code (e.g. serialization.h) will be generated as if these language options weren't set. (e.g. omit_float_serialization_support is always seen as None; hence all the float parsing functions will not be generated.)

Is this the expected behavior?

I'm not exactly sure where to post this, because the serialization support is still on its way, and I'm not sure if this issue would pop out on the current 0.3.9.

**Proposed Solution**
Maybe we can move the inference of the target language prior to the assignment of `language_context`?

**Comment by thirtytwobits** [comment]
This does seem like a bug in the CLI logic. I'm a bit backed up this week so I can't fix this until next. Feel free to submit a PR if you have time.
