### ISSUE TITLE
Extend C verification suite with different code generation and build options

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunavut#157]
As I am working on code generation, I need the test suite extended in a way similar to [what we have in Libcanard](https://github.com/UAVCAN/libcanard/blob/3e8f8037ca15e74c7e87efa5919b0873bd54feee/tests/CMakeLists.txt#L59-L90). In Nunavut there are various code generation and build options:

- target endianness: any, little, big
- target platform for native builds: x86 (-m32), AMD64
- serialization asserts: enabled, disabled
- optimization level: debug, release, min-size

We need the verification rigging updated to automatically run a test matrix covering every combination above.

@thirtytwobits @PetervdPerk-NXP would either of you volunteer?

FYI @TSC21

**Comment by thirtytwobits** [comment]
Okay. I'll take this one.
