### ISSUE TITLE
Specify line post-processor per language

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunavut#159]
I need Nunavut to apply `LimitEmptyLines(1)` and `TrimTrailingWhitespace()` to generated C outputs, but at the moment it is only possible to do so via CLI. There should be a way to specify this via language defaults.

@thirtytwobits would you be available to implement this?

**Comment by thirtytwobits** [comment]
Ah ya big baby. Okay. I'll add a way to automatically run LimitEmptyLines and TrimTrailingWhitespace but enabling these will slow down generation since we'll have to fallback to line buffered code generation. Can you not just write the jinja correctly?

**Comment by pavel-kirienko** [comment]
> Can you not just write the jinja correctly?

I can but I don't understand why should I bother? Managing whitespaces in any non-trivial template is tedious work that requires attention and adjustments; it is easy to automate away completely so why not do so?

This task is now a low-priority one because I implemented a workaround in https://github.com/UAVCAN/nunavut/commit/316b4f196727126a3d6c4d85105eadf6ec2a1d5a. Right now https://github.com/UAVCAN/nunavut/issues/157 is more critical.

**Comment by pavel-kirienko** [comment]
*(I also prefer garbage collected languages and cars with automatic transmission)*

**Comment by thirtytwobits** [comment]
> _(I also prefer garbage collected languages and cars with automatic transmission)_

You might find it funny to note that I despise garbage collected languages and I learned to drive using a standard transmission (and...I...liked it!)

**Comment by aentinger** [comment]
Everyone likes standard transmission, the fast and furious franchise saw to that :wink: That being said, I don't really dislike garbage collected languages but I don't trust them :wink: (Sorry, but I couldn't resist commenting when @thirtytwobits above comment flowed into my inbox.)
