### ISSUE TITLE
update jinja ahead of 1.0 release

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunavut#162]
We should try resyncing from upstream using my embed_jinja.py script. If it fails horribly we can defer this but if it's only a few fixes it'd be nice to be more up-to-date before we release.

**Comment by pavel-kirienko** [comment]
The script itself appears to require some fixing. I poked it slightly. It poked me back, so I decided not to proceed.

**Comment by thirtytwobits** [comment]
I tried it myself. My script is borked since upstream paths changed. Not a biggie. We'll defer this.
