### ISSUE TITLE
Put C++ and js behind an "experimental" flag

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunavut#172]
Since we want to release intrinsic support for C we need to disable the immature C++ and JS languages unless the user uses an "experimental" flag to make these available again. This blocks 1.0 release with C support.

**Comment by pavel-kirienko** [comment]
Are you sure this is really necessary considering that we state in the docs, on the front page, that only C is currently supported?

**Comment by thirtytwobits** [comment]
Yes. "1.0" is a promise that I want to be very careful with. It's easy to miss documentation that generated C++ will change and just as easy to specify `-l cpp` in nnvg.
