### ISSUE TITLE
Some line lost line break

### ISSUE THREAD

**Issue by Cherish-forever** [UAVCAN/nunavut#183]
I am using nunavt to generate C header file(cross compile for stm32f4xx), and there some file lost line break.
Here is index:
nunavut/support/serialization.h:27---->#include <string.h>#include <stdbool.h>
nunavut/support/serialization.h:379---->}#ifdef __cplusplus

and there is something wrong I don`t understand:
public_regulated_data_types/uavcan/node/Mode.1.0.uavcan is trying to use a serialization library that was compiled with different language options. This is dangerous and therefore not allowed."
static_assert( NUNAVUT_SUPPORT_LANGUAGE_OPTION_ENABLE_SERIALIZATION_ASSERTS == 1,

**Comment by Cherish-forever** [comment]
I have solved this issue.
remove  --enable-serialization-asserts

**Comment by thirtytwobits** [comment]
erp. Good find. Accepting.

**Comment by thirtytwobits** [comment]
Fixed. Release is in progress.
