### ISSUE TITLE
Folder name torque prefixed with "_" when generating C headers

### ISSUE THREAD

**Issue by aentinger** [UAVCAN/nunavut#188]
When generating C header files via `nnvg` invoked as shown below
```bash
nnvg --target-language c \
     --pp-max-emptylines=1  \
     --pp-trim-trailing-whitespace \
     --target-endianness=any \
     --enable-serialization-asserts \
     --outdir public_regulated_data_types/uavcan-header \
     public_regulated_data_types/uavcan
```
the folder name containing the generated header files of `si/sample/torque` is prefixed with a `_` (`si/sample/_torque`) although there's no reason for doing so (not a keyword as e.g. `register`).

**Comment by pavel-kirienko** [comment]
Also: `tandque` is not prefixed so it's not because of the `or` in `torque`.

**Comment by thirtytwobits** [comment]
I see the problem. It's because I've only provided a single set of identifier rules. According to the C standard (https://en.cppreference.com/w/c/language/identifier) to[a-z] is only reserved for function names.

**Comment by pavel-kirienko** [comment]
>According to the C standard (https://en.cppreference.com/w/c/language/identifier) to[a-z] is only reserved for function names.

Huh, I didn't know that. That means that it is not actually an implementation problem, is it? Do you think we should change the current behavior for C?

**Comment by thirtytwobits** [comment]
Sorry this is taking so long. I'm almost done. I have the fix after a complete refactor of the stropping code. I just need to clean up a few failing unit tests.

**Comment by thirtytwobits** [comment]
Fixed and released as https://pypi.org/project/nunavut/ 1.4.
Minor version bump since it will change the name of the generated paths where this bug affected them.

**Comment by pavel-kirienko** [comment]
Include paths generated for `#include` statements still contain prefixed path components:

```bash
~/test ❯ nnvg --version
1.5.1

~/test ❯ nnvg --target-language c ~/uavcan/public_regulated_data_types/reg --lookup-dir ~/uavcan/public_regulated_data_types/uavcan 

~/test ❯ cat nunavut_out/reg/udral/physics/dynamics/rotation/Planar_0_1.h | head -n 40 | tail -n 5 
#include <nunavut/support/serialization.h>
#include <reg/udral/physics/kinematics/rotation/Planar_0_1.h>
#include <uavcan/si/unit/_torque/Scalar_1_0.h>
#include <stdlib.h>
```

Note `#include <uavcan/si/unit/_torque/Scalar_1_0.h>`

**Comment by Cherish-Gww** [comment]
@pavel-kirienko 
Recently, we have encountered the same problem。
nunavut==1.2.2 is ok

**Comment by thirtytwobits** [comment]
Yep. Sorry. I have a fix in a branch. Will merge with the C++ variant work.

**Comment by pavel-kirienko** [comment]
Fixed in #220 

FYI @silverv

**Comment by thirtytwobits** [comment]
Unfortunately `register` is reserved in c and c++ so we can't safely generate code where this is used as an identifier. In Nunavut 2.0 (due out before the end of the year) we'll allow external overrides of the internal configuration. Doing that you can specify a different prefix for stropping or change the reserved keywords. See https://github.com/OpenCyphal/nunavut/blob/main/src/nunavut/lang/properties.yaml#L226

**Comment by Cherish-Gww** [comment]
> Unfortunately `register` is reserved in c and c++ so we can't safely generate code where this is used as an identifier. In Nunavut 2.0 (due out before the end of the year) we'll allow external overrides of the internal configuration. Doing that you can specify a different prefix for stropping or change the reserved keywords. See https://github.com/OpenCyphal/nunavut/blob/main/src/nunavut/lang/properties.yaml#L226

We are using the nnvg tool to generate c files and h files, and we have changed lang j2 file to generate canard object in c file. 
Can't wait to use Nunavut 2.0.0, Thank you very much.
