### ISSUE TITLE
[C] Attach type version numbers to service types rather than nested request/response

### ISSUE THREAD

**Issue by Cherish-forever** [UAVCAN/nunavut#190]
exp:
#define uavcan_node_ExecuteCommand_Request_1_1_EXTENT_BYTES_                    300UL
#define uavcan_node_ExecuteCommand_Request_1_1_SERIALIZATION_BUFFER_SIZE_BYTES_ 258UL

I think define like this will be better:
#define uavcan_node_ExecuteCommand_1_1_Request_EXTENT_BYTES_                    300UL
#define uavcan_node_ExecuteCommand_1_1_Request_SERIALIZATION_BUFFER_SIZE_BYTES_ 258UL

it will be easy to replace string "ExecuteCommand_1_1" for different version or different protocol.

**Comment by pavel-kirienko** [comment]
Somewhat relevant discussion here: https://github.com/UAVCAN/nunavut/pull/155

Either format should work but I don't think it's worth changing it just for the sake of auto-renaming convenience.

**Comment by thirtytwobits** [comment]
Unfortunately we've already discussed where the version should be and decided it belongs on the request and response types. This isn't something we want to make a major/breaking change for even if we could be convinced to change our previous decision. Sorry.
