### ISSUE TITLE
Missing escape characters for DSDL source file path in Windows

### ISSUE THREAD

**Issue by aasmune** [UAVCAN/nunavut#195]
**Problem description**
When generating C headers on Windows with, the DSDL source file paths are generated incorrectly, causing compile-time warnings, e.g: `warning: unknown escape sequence: '\U'`. This is caused by the backslashes not being escaped properly:
```C
static_assert( NUNAVUT_SUPPORT_LANGUAGE_OPTION_TARGET_ENDIANNESS == 434322821,
              "C:\Users\aasme\Documents\git\uavcan\public_regulated_data_types\uavcan\node\7509.Heartbeat.1.0.uavcan is trying to use a serialization library that was compiled with "
              "different language options. This is dangerous and therefore not allowed." );
static_assert( NUNAVUT_SUPPORT_LANGUAGE_OPTION_OMIT_FLOAT_SERIALIZATION_SUPPORT == 0,
              "C:\Users\aasme\Documents\git\uavcan\public_regulated_data_types\uavcan\node\7509.Heartbeat.1.0.uavcan is trying to use a serialization library that was compiled with "
              "different language options. This is dangerous and therefore not allowed." );
static_assert( NUNAVUT_SUPPORT_LANGUAGE_OPTION_ENABLE_SERIALIZATION_ASSERTS == 1,
              "C:\Users\aasme\Documents\git\uavcan\public_regulated_data_types\uavcan\node\7509.Heartbeat.1.0.uavcan is trying to use a serialization library that was compiled with "
              "different language options. This is dangerous and therefore not allowed." );
static_assert( NUNAVUT_SUPPORT_LANGUAGE_OPTION_ENABLE_OVERRIDE_VARIABLE_ARRAY_CAPACITY == 0,
              "C:\Users\aasme\Documents\git\uavcan\public_regulated_data_types\uavcan\node\7509.Heartbeat.1.0.uavcan is trying to use a serialization library that was compiled with "
              "different language options. This is dangerous and therefore not allowed." );
```

**Proposed Solution**
Either escape the backslash properly or change to Posix paths as in #129. I would suggest the latter.

**System info:**
_Nunavut version:_ 1.0.3
_System OS:_ Windows 10

**Comment by pavel-kirienko** [comment]
Hi Aasmund! I thought this issue was fixed in #129 because it explicitly calls `as_posix()` when emitting code. @edwinbalani can you please share your experience?

**Comment by edwinbalani** [comment]
It looks like in #168, which fixed #129, `as_posix()` was only performed in generation of `#include` lines.  On the other hand, here we are relying on the `nunavut.Namespace.source_file_path` property function, returning `str`:

```python
class Namespace(pydsdl.Any):
     # snip
     @property
     def source_file_path(self) -> str:
         return str(self._source_folder)
```

So yes, this is a separate unfixed bug.

The quick fix here is to change the return value to `self._source_folder.as_posix()`, but I think a PR for this should go through the whole of nunavut and inspect uses of `pathlib.Path` or `pathlib.PurePath` objects, to weed out any similar instances of weak path handling once and for all.

**Comment by pavel-kirienko** [comment]
Thanks Edwin. Would either of you volunteer to fix it?

**Comment by aasmune** [comment]
> The quick fix here is to change the return value to `self._source_folder.as_posix()`, 

First, I also believed that this quick fix would solve the issue, and I attempted to do the proposed change locally, but it didn't work. I'm not familiar with the inner workings of _nunavut_, but I did some basic debugging of `nnvg` by setting a breakpoint at this line, but the breakpoint never triggered which I found suspicious. However, I don't know if something with the jinja2 template rendering prevents the python debugger to detect and break at the breakpoint, or if the method isn't called at all.

**Comment by Polarisru** [comment]
I have the same problem with Nunavut version: 1.2.0

**Comment by Polarisru** [comment]
> 
> 
> > The quick fix here is to change the return value to `self._source_folder.as_posix()`,
> 
> First, I also believed that this quick fix would solve the issue, and I attempted to do the proposed change locally, but it didn't work. I'm not familiar with the inner workings of _nunavut_, but I did some basic debugging of `nnvg` by setting a breakpoint at this line, but the breakpoint never triggered which I found suspicious. However, I don't know if something with the jinja2 template rendering prevents the python debugger to detect and break at the breakpoint, or if the method isn't called at all.

I have also tried to fix it locally with the same result, this function is never called.

**Comment by DNedic** [comment]
I tried replacing T.source_file_path with T.source_file_path | replace("\\", "\\\\") base.j2 and StructureType.j2 and this did the trick as a quick fix, i am unsure about whethter this is a good solution overall, but not being able to build on windows seems like a huge oversight.

**Comment by pavel-kirienko** [comment]
@DNedic can you please submit a pull request with that quick fix? It doesn't actually look too bad to me. While submitting the pull request, please do bump the patch version. Thanks!

**Comment by DNedic** [comment]
@pavel-kirienko Sure, will do so asap.
