### ISSUE TITLE
Stropping

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunavut#23]
DSDL definitions may contain identifiers which may not be allowed in some programming languages. This library should provide a way for the caller to specify which identifiers are not allowed. Upon encountering such identifiers, pydsdlgen would extend them as specified by the caller. For example:

* in Rust, the identifier would be prefixed with `r#` to form a raw identifier: `if` --> `r#if`
* in Python or C++ there is no concept of raw identifier; a common practice is to append an underscore: `if` --> `if_`. This, however, may lead to another name conflict if the source definition contains both `x_` and `x` for some x.
* Nim uses a pair of backticks: `if` --> `` `if` ``

Here, for example, is a list of reserved identifiers in Python 3.7:

```python
>>> import keyword, builtins
>>> list(sorted(keyword.kwlist + dir(builtins)))
['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError',
'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError',
'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError',
'Exception', 'False', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning',
'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError',
'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError',
'None', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError',
'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError',
'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError',
'SyntaxWarning', 'SystemError', 'SystemExit', 'TabError', 'TimeoutError', 'True', 'True', 'TypeError',
'UnboundLocalError', 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeError', 'UnicodeTranslateError',
'UnicodeWarning', 'UserWarning', 'ValueError', 'Warning', 'ZeroDivisionError', '_', '__build_class__', '__debug__',
'__doc__', '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'all', 'and', 'any', 'as',
'ascii', 'assert', 'async', 'await', 'bin', 'bool', 'break', 'breakpoint', 'bytearray', 'bytes', 'callable', 'chr',
'class', 'classmethod', 'compile', 'complex', 'continue', 'copyright', 'credits', 'def', 'del', 'delattr', 'dict',
'dir', 'divmod', 'elif', 'else', 'enumerate', 'eval', 'except', 'exec', 'exit', 'filter', 'finally', 'float', 'for',
'format', 'from', 'frozenset', 'getattr', 'global', 'globals', 'hasattr', 'hash', 'help', 'hex', 'id', 'if', 'import',
'in', 'input', 'int', 'is', 'isinstance', 'issubclass', 'iter', 'lambda', 'len', 'license', 'list', 'locals', 'map',
'max', 'memoryview', 'min', 'next', 'nonlocal', 'not', 'object', 'oct', 'open', 'or', 'ord', 'pass', 'pow', 'print',
'property', 'quit', 'raise', 'range', 'repr', 'return', 'reversed', 'round', 'set', 'setattr', 'slice', 'sorted',
'staticmethod', 'str', 'sum', 'super', 'try', 'tuple', 'type', 'vars', 'while', 'with', 'yield', 'zip']
```

One can easily define an external Jinja filter for mangling attribute names as necessary. Namespaces and type names, on the other hand, are handled entirely under the hood, so the user won't be able to implement mangling unless it is explicitly supported by the library. It makes sense to define a global filter capable of mangling names in all contexts: attributes, namespaces, and type names. It's best to find a short name for it, like `id`, because it is expected to occur in templates very frequently.

**Comment by thirtytwobits** [comment]
I think this would be better implemented as a [JINJA extension](http://jinja.pocoo.org/docs/2.10/extensions/) than a filter.

**Comment by pavel-kirienko** [comment]
Can we please register it for the v1.0 milestone? This is rather important.

**Comment by pavel-kirienko** [comment]
> rewrite Nunavut as an LLVM transpiler

I don't understand how is this compatible with languages that are not supported by LLVM (Python). Might need more discussion?

> for C/C++ and python we simply need a "make keyword safe" filter.

Filters are needed, but they are not sufficient because we also need to apply mangling/stropping for entities that are generated directly by Nunavut outside of templates, such as namespace directories and source files. If I have a DSDL namespace named `pass`, I won't be able to generate Python packages from that unless I can instruct Nunavut to mangle `pass` along with the other Python keywords.
