### ISSUE TITLE
Create default dsdl documentation generation templates

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunavut#29]
Provide a default set of templates to allow generation of documentation from dsdl.

Note that this is blocked on https://github.com/UAVCAN/pydsdl/issues/21

**Comment by pavel-kirienko** [comment]
Unblocked by https://github.com/UAVCAN/pydsdl/pull/65

Related post: https://forum.uavcan.org/t/generate-rich-navigable-html-docs-using-nunavut/1163

**Comment by thirtytwobits** [comment]
woot

**Comment by pavel-kirienko** [comment]
Fixed in #201, thanks @bbworld1
