### ISSUE TITLE
Move build to UAVCAN AWS Account

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunavut#77]
add free-tier hosts to our buildkite pool with a different tag. Use these for python builds.

**Comment by thirtytwobits** [comment]
@pavel-kirienko , any chance we can get that AWS account setup for UAVCAN?

**Comment by pavel-kirienko** [comment]
Yes. We spoke about it but never got it going because the priority was considered to be too low to care.

@clyde-johnston can you please look into it? Scott will provide the technical details since it is currently hosted on his personal account.

**Comment by clyde-johnston** [comment]
@thirtytwobits Hi Scott, could you please fill me in on the requirements?  I am new to this.  What are we trying to do?  How do you want to achieve it?

**Comment by pavel-kirienko** [comment]
Related https://github.com/UAVCAN/nunavut/issues/60

**Comment by pavel-kirienko** [comment]
@thirtytwobits is this still relevant?

**Comment by thirtytwobits** [comment]
nope
